version: "3.2"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    networks:
        - apm-demo

  mssqldb:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: $MSSQL_PASSWORD
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
        - apm-demo

  redis:
    image: redis
    command: redis-server /redis.conf
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: ./config/redis.conf
        target: /redis.conf
    networks:
        - apm-demo

  rabbit:
      image: rabbitmq:management
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - apm-demo

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - type: bind
          source: ./config/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
          read_only: true
        - type: volume
          source: elasticsearch
          target: /usr/share/elasticsearch/data
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        ELASTIC_PASSWORD: $ES_PASSWORD
        discovery.type: single-node
      networks:
        - apm-demo

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: $ES_PASSWORD
    ports:
      - 5601:5601
    networks:
      - apm-demo

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.10.1
    command:
      - --strict.perms=false
    volumes:
      - type: bind
        source: ./config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
    ports:
      - 8200:8200
    networks:
      - apm-demo

networks:
  apm-demo:
    driver: bridge

volumes:
  elasticsearch: